version: '3.9'

services:
  db:
    container_name: pg_container
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: lokerian
      POSTGRES_PASSWORD: lokerian
      POSTGRES_DB: db_lokerian
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  adminer:
    container_name: adminer_container
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - '5050:8080'

  # Enable this for alternative database tool (pgadmin)
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   depends_on:
  #     - db
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - '5050:80'

volumes:
  pg_data:
    driver: local
